import type { DeployResult } from '@/types';
import { Octokit } from '@octokit/rest';

function getOctokit(token?: string): Octokit {
  const tk = token || process.env.GITHUB_TOKEN;
  if (!tk) throw new Error('GitHub token required. Set GITHUB_TOKEN env var or provide a token.');
  return new Octokit({ auth: tk });
}

function parseRepoUrl(url: string): { owner: string; repo: string } | null {
  const match = url.match(/github\.com[:\/]([\w.-]+)\/([\w.-]+?)(?:\.git)?$/);
  if (!match) return null;
  return { owner: match[1], repo: match[2].replace(/\.git$/, '') };
}

export async function deployToGitHub(
  siteName: string,
  files: Record<string, string>,
  repoUrl?: string,
  githubToken?: string
): Promise<DeployResult> {
  try {
    const octokit = getOctokit(githubToken);
    const user = await octokit.users.getAuthenticated();
    const owner = user.data.login;

    let repoName: string;
    let repo;

    if (repoUrl) {
      const parsed = parseRepoUrl(repoUrl);
      if (!parsed) {
        return { repoUrl: '', pagesUrl: '', success: false, message: 'Invalid GitHub URL. Use format: https://github.com/username/repo' };
      }
      repoName = parsed.repo;

      try {
        repo = await octokit.repos.get({ owner: parsed.owner, repo: repoName });
        if (!repo.data.permissions?.push) {
          return { repoUrl: '', pagesUrl: '', success: false, message: 'You do not have push access to this repo.' };
        }
        repoName = repo.data.name;
      } catch {
        return { repoUrl: '', pagesUrl: '', success: false, message: `Repo "${parsed.owner}/${repoName}" not found. Check the URL and make sure it exists.` };
      }
    } else {
      repoName = siteName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 100) || 'kyron-site';
      try {
        repo = await octokit.repos.createForAuthenticatedUser({
          name: repoName,
          description: `Site generated by Kyron — ${siteName}`,
          auto_init: true,
          private: false,
        });
      } catch (err: any) {
        if (err.status === 422) {
          return { repoUrl: '', pagesUrl: '', success: false, message: `Repo "${repoName}" already exists. Provide a repo URL instead.` };
        }
        throw err;
      }
    }

    const repo_full_name = repo.data.full_name || `${owner}/${repoName}`;
    const [repoOwner, repoNameOnly] = repo_full_name.split('/');

    // Get the latest commit SHA to base our commit on
    let sha: string;
    try {
      const ref = await octokit.git.getRef({ owner: repoOwner, repo: repoNameOnly, ref: 'heads/main' });
      sha = ref.data.object.sha;
    } catch {
      try {
        const ref = await octokit.git.getRef({ owner: repoOwner, repo: repoNameOnly, ref: 'heads/master' });
        sha = ref.data.object.sha;
      } catch {
        return { repoUrl: '', pagesUrl: '', success: false, message: 'Could not find main or master branch.' };
      }
    }

    const baseTree = (await octokit.git.getTree({ owner: repoOwner, repo: repoNameOnly, tree_sha: sha })).data;

    const blobs = await Promise.all(
      Object.entries(files).map(async ([path, content]) => {
        const blob = await octokit.git.createBlob({
          owner: repoOwner,
          repo: repoNameOnly,
          content: Buffer.from(content).toString('base64'),
          encoding: 'base64',
        });
        return { path, mode: '100644' as const, type: 'blob' as const, sha: blob.data.sha };
      })
    );

    const newTree = await octokit.git.createTree({
      owner: repoOwner,
      repo: repoNameOnly,
      base_tree: baseTree.sha,
      tree: blobs,
    });

    const commit = await octokit.git.createCommit({
      owner: repoOwner,
      repo: repoNameOnly,
      message: `Site generated by Kyron — ${siteName}`,
      tree: newTree.data.sha,
      parents: [sha],
    });

    const branch = sha.includes('master') ? 'master' : 'main';
    await octokit.git.updateRef({
      owner: repoOwner,
      repo: repoNameOnly,
      ref: `heads/${branch}`,
      sha: commit.data.sha,
    });

    try {
      await octokit.repos.createPagesSite({
        owner: repoOwner,
        repo: repoNameOnly,
        source: { branch, path: '/' },
      });
    } catch { /* pages may already be enabled */ }

    let pagesUrl = '';
    try {
      const pages = await octokit.repos.getPages({ owner: repoOwner, repo: repoNameOnly });
      pagesUrl = pages.data.html_url || '';
    } catch {
      pagesUrl = `https://${repoOwner}.github.io/${repoNameOnly}`;
    }

    return {
      repoUrl: `https://github.com/${repoOwner}/${repoNameOnly}`,
      pagesUrl,
      success: true,
      message: `Deployed! View at ${pagesUrl}`,
    };
  } catch (err: any) {
    return {
      repoUrl: '',
      pagesUrl: '',
      success: false,
      message: err.message || 'Deployment failed',
    };
  }
}
