import type { DeployResult } from '@/types';
import { Octokit } from '@octokit/rest';

function getOctokit(): Octokit {
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    throw new Error('GITHUB_TOKEN environment variable is not set');
  }
  return new Octokit({ auth: token });
}

export async function deployToGitHub(
  siteName: string,
  files: Record<string, string>,
  githubToken?: string
): Promise<DeployResult> {
  try {
    const octokit = githubToken
      ? new Octokit({ auth: githubToken })
      : getOctokit();

    const user = await octokit.users.getAuthenticated();
    const repoName = siteName
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 100) || 'kyron-site';

    let repo;
    try {
      repo = await octokit.repos.createForAuthenticatedUser({
        name: repoName,
        description: `Site generated by Kyron - ${siteName}`,
        auto_init: true,
        private: false,
      });
    } catch (err: any) {
      if (err.status === 422) {
        return {
          repoUrl: '',
          pagesUrl: '',
          success: false,
          message: `Repository "${repoName}" already exists. Try a different project name.`,
        };
      }
      throw err;
    }

    const owner = user.data.login;
    const repo_name = repo.data.name;

    const sha = (await octokit.git.getRef({
      owner,
      repo: repo_name,
      ref: 'heads/main',
    })).data.object.sha;

    const baseTree = (await octokit.git.getTree({
      owner,
      repo: repo_name,
      tree_sha: sha,
    })).data;

    const blobs = await Promise.all(
      Object.entries(files).map(async ([path, content]) => {
        const blob = await octokit.git.createBlob({
          owner,
          repo: repo_name,
          content: Buffer.from(content).toString('base64'),
          encoding: 'base64',
        });
        return {
          path,
          mode: '100644' as const,
          type: 'blob' as const,
          sha: blob.data.sha,
        };
      })
    );

    const newTree = await octokit.git.createTree({
      owner,
      repo: repo_name,
      base_tree: baseTree.sha,
      tree: blobs,
    });

    const commit = await octokit.git.createCommit({
      owner,
      repo: repo_name,
      message: `Initial commit — site generated by Kyron`,
      tree: newTree.data.sha,
      parents: [sha],
    });

    await octokit.git.updateRef({
      owner,
      repo: repo_name,
      ref: 'heads/main',
      sha: commit.data.sha,
    });

    try {
      await octokit.repos.createPagesSite({
        owner,
        repo: repo_name,
        source: { branch: 'main', path: '/' },
      });
    } catch {
      // Pages might already be enabled or not available
    }

    let pagesUrl = '';
    try {
      const pages = await octokit.repos.getPages({
        owner,
        repo: repo_name,
      });
      pagesUrl = pages.data.html_url || '';
    } catch {
      pagesUrl = `https://${owner}.github.io/${repo_name}`;
    }

    return {
      repoUrl: repo.data.html_url,
      pagesUrl,
      success: true,
      message: `Site deployed! View at ${pagesUrl}`,
    };
  } catch (err: any) {
    return {
      repoUrl: '',
      pagesUrl: '',
      success: false,
      message: err.message || 'Failed to deploy to GitHub',
    };
  }
}
